### PR TITLE
Fixed some docs

### LINKED ISSUE #191: Small documentation/cleanup tasks
- [ ]  Add documentation for some of the Utilities functions that are missing it.
- [ ]  Remove unneeded comments from top of linescan test file that are talking about problems that no longer exist ("commented out tests...")

### PR DESCRIPTION
**Pull request by jessemapel**
Fixes #191

### CODE REVIEW

File: src/Utilities.cpp [hunk 1]
```diff
@@ -48,6 +52,16 @@ void calculateRotationMatrixFromQuaternions(
   rotationMatrix[8] = -q[0] * q[0] - q[1] * q[1] + q[2] * q[2] + q[3] * q[3];
 }
 
+// Compue the distorted focal plane coordinate for a given image pixel
+// in - line
+// in - sample
+// in - sampleOrigin - the origin of the ccd coordinate system relative to the top left of the ccd
+// in - lineOrigin - the origin of the ccd coordinate system relative to the top left of the ccd
+// in - sampleSumming
+// in - startingSample - first ccd for the image
```
Comment (kberryUSGS) [inline src/Utilities.cpp]: ccd -> sample?

File: src/Utilities.cpp [hunk 2]
```diff
@@ -48,6 +52,16 @@ void calculateRotationMatrixFromQuaternions(
...
+// in - iTransS[3] - the transformation from focal plane to ccd samples
+// in - itransL[3] - the transformation from focal plane to ccd lines
```
Comment (kberryUSGS) [inline src/Utilities.cpp]: itranslL -> iTransL
